[package]
name = "client"
version = "0.1.0"
authors = ["LuÃ­s Fiolhais <luisazenhas.fiolhais@openmailbox.org>"]

[dependencies]
fenix_rooms = { path = ".." }
clap = { version = "~2.19.0", features = ["yaml"] }
toml = { version = "0.2.1", features = ["serde"] }
